security:
    # Настройка хэширования паролей
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    # Настройка провайдеров пользователей
    providers:
        # Пример: провайдер для пользователей из базы данных
        app_user_provider:
            entity:
                class: App\Entity\User # Убедитесь, что класс User существует
                property: email

    # Настройка firewall
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
            logout:
                path: /api/logout
                target: /
            # Добавьте другие методы аутентификации, если необходимо
    # Контроль доступа
    access_control:
        - { path: ^/api/protected, roles: ROLE_USER } # Пример ограничения доступа
